using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace vsroleplayclasses.src
{
    public enum ExtendedEnumDamageType
    {
        // Base VS types
        Gravity = 0,
        Fire = 1,
        BluntAttack = 2,
        SlashingAttack = 3,
        PiercingAttack = 4,
        Suffocation = 5,
        Heal = 6,
        Poison = 7,
        Hunger = 8,
        Crushing = 9,
        Frost = 10,

        Warrior_Magic = 100,
        Warrior_Fire = 101,
        Warrior_Cold = 102,
        Warrior_Poison = 103,
        Warrior_Disease = 104,
        Warrior_Chromatic = 105,
        Warrior_Prismatic = 106,
        Warrior_Physical = 107,
        Warrior_Corruption = 108,

        Cleric_Magic = 200,
        Cleric_Fire = 201,
        Cleric_Cold = 202,
        Cleric_Poison = 203,
        Cleric_Disease = 204,
        Cleric_Chromatic = 205,
        Cleric_Prismatic = 206,
        Cleric_Physical = 207,
        Cleric_Corruption = 208,

        Paladin_Magic = 300,
        Paladin_Fire = 301,
        Paladin_Cold = 302,
        Paladin_Poison = 303,
        Paladin_Disease = 304,
        Paladin_Chromatic = 305,
        Paladin_Prismatic = 306,
        Paladin_Physical = 307,
        Paladin_Corruption = 308,

        Ranger_Magic = 400,
        Ranger_Fire = 401,
        Ranger_Cold = 402,
        Ranger_Poison = 403,
        Ranger_Disease = 404,
        Ranger_Chromatic = 405,
        Ranger_Prismatic = 406,
        Ranger_Physical = 407,
        Ranger_Corruption = 408,

        Shadowknight_Magic = 500,
        Shadowknight_Fire = 501,
        Shadowknight_Cold = 502,
        Shadowknight_Poison = 503,
        Shadowknight_Disease = 504,
        Shadowknight_Chromatic = 505,
        Shadowknight_Prismatic = 506,
        Shadowknight_Physical = 507,
        Shadowknight_Corruption = 508,

        Druid_Magic = 600,
        Druid_Fire = 601,
        Druid_Cold = 602,
        Druid_Poison = 603,
        Druid_Disease = 604,
        Druid_Chromatic = 605,
        Druid_Prismatic = 606,
        Druid_Physical = 607,
        Druid_Corruption = 608,

        Monk_Magic = 700,
        Monk_Fire = 701,
        Monk_Cold = 702,
        Monk_Poison = 703,
        Monk_Disease = 704,
        Monk_Chromatic = 705,
        Monk_Prismatic = 706,
        Monk_Physical = 707,
        Monk_Corruption = 708,

        Bard_Magic = 800,
        Bard_Fire = 801,
        Bard_Cold = 802,
        Bard_Poison = 803,
        Bard_Disease = 804,
        Bard_Chromatic = 805,
        Bard_Prismatic = 806,
        Bard_Physical = 807,
        Bard_Corruption = 808,

        Shaman_Magic = 900,
        Shaman_Fire = 901,
        Shaman_Cold = 902,
        Shaman_Poison = 903,
        Shaman_Disease = 904,
        Shaman_Chromatic = 905,
        Shaman_Prismatic = 906,
        Shaman_Physical = 907,
        Shaman_Corruption = 908,

        Necromancer_Magic = 1000,
        Necromancer_Fire = 1001,
        Necromancer_Cold = 1002,
        Necromancer_Poison = 1003,
        Necromancer_Disease = 1004,
        Necromancer_Chromatic = 1005,
        Necromancer_Prismatic = 1006,
        Necromancer_Physical = 1007,
        Necromancer_Corruption = 1008,

        Wizard_Magic = 1100,
        Wizard_Fire = 1101,
        Wizard_Cold = 1102,
        Wizard_Poison = 1103,
        Wizard_Disease = 1104,
        Wizard_Chromatic = 1105,
        Wizard_Prismatic = 1106,
        Wizard_Physical = 1107,
        Wizard_Corruption = 1108,

        Magician_Magic = 1200,
        Magician_Fire = 1201,
        Magician_Cold = 1202,
        Magician_Poison = 1203,
        Magician_Disease = 1204,
        Magician_Chromatic = 1205,
        Magician_Prismatic = 1206,
        Magician_Physical = 1207,
        Magician_Corruption = 1208,

        Enchanter_Magic = 1300,
        Enchanter_Fire = 1301,
        Enchanter_Cold = 1302,
        Enchanter_Poison = 1303,
        Enchanter_Disease = 1304,
        Enchanter_Chromatic = 1305,
        Enchanter_Prismatic = 1306,
        Enchanter_Physical = 1307,
        Enchanter_Corruption = 1308,

        Beastlord_Magic = 1400,
        Beastlord_Fire = 1401,
        Beastlord_Cold = 1402,
        Beastlord_Poison = 1403,
        Beastlord_Disease = 1404,
        Beastlord_Chromatic = 1405,
        Beastlord_Prismatic = 1406,
        Beastlord_Physical = 1407,
        Beastlord_Corruption = 1408,

        Berserker_Magic = 1500,
        Berserker_Fire = 1501,
        Berserker_Cold = 1502,
        Berserker_Poison = 1503,
        Berserker_Disease = 1504,
        Berserker_Chromatic = 1505,
        Berserker_Prismatic = 1506,
        Berserker_Physical = 1507,
        Berserker_Corruption = 1508
    }
}
